version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        BASE_IMAGE: "${DOCKER_LOCAL_REGISTRY}/development"
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    networks:
      - pybackpack_network
  redis:
    image: redis/redis-stack
    networks:
      - pybackpack_network
  mongo:
    image: mongo
    networks:
      - pybackpack_network

networks:
  pybackpack_network:
    driver: bridge
